### ISSUE TITLE
使用node-wechat的send方法时一直提示时间之类的错误

### ISSUE THREAD

**Issue by MarlonFan** [nswbmw/node-wechat#4]
[15:23:00]
[15:23:00] events.js:72
[15:23:00]         throw er; // Unhandled 'error' event
                         ^
[15:23:00] Error: Can't set headers after they are sent.
               at ServerResponse.OutgoingMessage.setHeader (http.js:690:11)
               at ServerResponse.setWriteHeadHeaders (/Users/marlon/code/zm-www/node_modules/express-session/node_modules/on-headers/index.js:80:19)
               at ServerResponse.writeHead (/Users/marlon/code/zm-www/node_modules/express-session/node_modules/on-headers/index.js:39:36)
               at [object Object].Wechat.send (/Users/marlon/code/zm-www/node_modules/node-wechat/index.js:259:12)
               at EventEmitter.<anonymous> (/Users/marlon/code/zm-www/server/api/wechat.ts:71:20)
               at EventEmitter.emit (events.js:117:20)
               at /Users/marlon/code/zm-www/node_modules/node-wechat/index.js:66:17
               at Parser.<anonymous> (/Users/marlon/code/zm-www/node_modules/node-wechat/node_modules/xml2js/lib/xml2js.js:462:18)
               at Parser.emit (events.js:95:17)
               at Object.onclosetag (/Users/marlon/code/zm-www/node_modules/node-wechat/node_modules/xml2js/lib/xml2js.js:423:26)
               at emit (/Users/marlon/code/zm-www/node_modules/node-wechat/node_modules/xml2js/node_modules/sax/lib/sax.js:625:33)
               at emitNode (/Users/marlon/code/zm-www/node_modules/node-wechat/node_modules/xml2js/node_modules/sax/lib/sax.js:630:3)
               at closeTag (/Users/marlon/code/zm-www/node_modules/node-wechat/node_modules/xml2js/node_modules/sax/lib/sax.js:874:5)
               at Object.write (/Users/marlon/code/zm-www/node_modules/node-wechat/node_modules/xml2js/node_modules/sax/lib/sax.js:1314:29)
               at Parser.exports.Parser.Parser.parseString (/Users/marlon/code/zm-www/node_modules/node-wechat/node_modules/xml2js/lib/xml2js.js:481:31)
               at Parser.parseString (/Users/marlon/code/zm-www/node_modules/node-wechat/node_modules/xml2js/lib/xml2js.js:7:59)

**Comment by MarlonFan** [comment]
sorry 我自己框架的问题. 封装了其他的api..
